### PR TITLE
personal-portfolio-webpage

### PR DESCRIPTION
**Pull request by humuyar**
#: I added a html file for personal portfolio webpage.
#: I added a linter config
#: I added a CSS for designing my Web page.

### CODE REVIEW

**Comment by humuyar** [comment]
@ahzamir
I done my  personal-portfolio-webpage

**Comment by humuyar** [comment]
@ahzamir
I done my personal portfolio webpage

**Comment by humuyar** [comment]
@ahzamir
I done my personal portfolio webpage

**Review by ahzamir — CHANGES_REQUESTED** [review]
### Hi @humuyar 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website Personal Portfolio project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.
  - Your code missing just one of the checks.
  
# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞
 
🎯 Great Design implemented.
image

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Personal Portfolio and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your project has a professional README.md file
✔️Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by humuyar** [comment]
@ahzamir 
Sir ma ky code hayie ma pass mekonum da freecodecamp bar ma check megera ama part css sha ky pak mekonum baz two da yeash check namesha

**Comment by ahzamir** [comment]
> @ahzamir Sir ma ky code hayie ma pass mekonum da freecodecamp bar ma check megera ama part css sha ky pak mekonum baz two da yeash check namesha

@humuyar 

- Your code is missing `Failed:Your portfolio should use at least one media query.` This requirement, which says you don't have any media query n your code and I checked your CSS code you don't have it.

**Comment by humuyar** [comment]
@ahzamir 
sir  i apply the feedback

**Review by ahzamir — APPROVED** [review]
### Hi @iamfarhatsharefi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Personal Portfolio Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by ahzamir** [comment]
@humuyar 

- Don't forget to deploy your project and add the deployed link in your README.md file, then ask your partner to review it.

**Pull request merged**
